In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
a[0]

1

In [3]:
a = ([1,2,3,4,5])
b = ([6,7,8,9,10])
a[0],a[1]

(1, 2)

In [4]:
a[0:]

[1, 2, 3, 4, 5]

In [5]:
b[1:3]

[7, 8]

In [6]:
a[1:-1]

[2, 3, 4]

In [7]:
b[::2]

[6, 8, 10]

In [8]:
b[2],b[3],b[4]

(8, 9, 10)

In [9]:
type(a)

list

In [10]:
a = np.array([
    [
        [1,2,3,4],
        [3,4,5,6]
    ],
    [
        [8,9,7,10],
        [2,5,8,3]
    ]
])
a

array([[[ 1,  2,  3,  4],
        [ 3,  4,  5,  6]],

       [[ 8,  9,  7, 10],
        [ 2,  5,  8,  3]]])

In [11]:
a.shape

(2, 2, 4)

In [12]:
a.ndim

3

In [13]:
a.size

16

In [14]:
a.dtype

dtype('int32')

In [15]:

b = np.array([
    #0 #1 #2
    [1,2,3], #0
    [4,5,6], #1
    [7,8,9]  #2
])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
b.size

9

In [17]:
b[1][2]

6

In [18]:
b[1] = np.array([10,20,30])

In [19]:
b

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 7,  8,  9]])

In [20]:
b[2] = 56

In [21]:
b

array([[ 1,  2,  3],
       [10, 20, 30],
       [56, 56, 56]])

In [22]:
b[0:]

array([[ 1,  2,  3],
       [10, 20, 30],
       [56, 56, 56]])

In [23]:
b[1:,2:]

array([[30],
       [56]])

In [24]:
b[1:,1:]

array([[20, 30],
       [56, 56]])

In [25]:
b[2:,1:]

array([[56, 56]])

In [26]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [27]:
a.sum()

45

In [28]:
a.mean()

5.0

In [29]:
a.std()

2.581988897471611

In [30]:
a.var()

6.666666666666667

In [31]:
a.sum(axis=0)

array([12, 15, 18])

In [32]:
a.sum(axis=1)

array([ 6, 15, 24])

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [35]:
l = [1,2,3,4]
[i * 10 for i in l]

[10, 20, 30, 40]

In [36]:
a = np.array([1,2,3,4])
a + l

array([2, 4, 6, 8])

In [37]:
a = np.arange(5)

In [38]:
a
a + 20

array([20, 21, 22, 23, 24])

In [39]:
c = np.array([1,2,3,4])
c * 10

array([10, 20, 30, 40])

# Boolean operations on arrays

In [40]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [41]:
a[0:3]

array([0, 1, 2])

In [42]:
a[0:-1]

array([0, 1, 2])

In [43]:
a[[0,-1]]

array([0, 3])

In [44]:
a >= 2

array([False, False,  True,  True])

In [45]:
a.mean()

1.5

In [46]:
a.sum()

6

In [47]:
a.std()

1.118033988749895

In [48]:
a.var()

1.25

In [49]:
a[(a == 0)|(a == 1)]

array([0, 1])

In [50]:
a[a > a.mean()]

array([2, 3])

In [51]:
a[~(a > a.mean())]

array([0, 1])

In [52]:
a[(a <= 2)&(a % 2 == 0)]

array([0, 2])

# Linear Algebra

In [53]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [54]:
b = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [55]:
a.dot(b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [56]:
a @ b

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [57]:
b.T

array([[1, 3, 5],
       [2, 4, 6]])

In [58]:
b.T @ a

array([[48, 57, 66],
       [60, 72, 84]])

In [59]:
import sys
import numpy as np
sys.getsizeof(1)

28

In [60]:
sys.getsizeof(10**100)

72

In [61]:
np.dtype(int).itemsize

4

In [62]:
np.dtype(float).itemsize

8

In [63]:
sys.getsizeof([1])

72

In [64]:
np.array([1]).nbytes

4

# Performance

In [65]:
l = list(range(1000))

In [66]:
a = np.arange(1000)

In [67]:
%time np.sum(a ** 2)

Wall time: 0 ns


332833500

In [68]:
%time sum([x ** 2 for x in l])

Wall time: 992 µs


332833500

In [69]:
import numpy as np
def calculate(self):
    a = np.array([
        [1,2,3]
    ])
    return calculate()
print(a.sum())

499500


In [70]:
a = np.array([1,2,3])
a.sum()

6